# See https://github.com/pmarsceill/just-the-docs/blob/master/_config.yml

title: "jackt8's Guide to Chunky"
description: "A guide to Chunky made by jackjt8"
baseurl: "/ChunkyGuide"

remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Aux links for the upper right navigation
aux_links:
  "My GitHub":
    - "https://github.com/jackjt8"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 jackjt8. Distributed by an <a href=\"https://github.com/jackjt8/ChunkyGuide/blob/master/LICENSE\">GNU license.</a>"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-45248997-1

plugins:
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html
